### ISSUE TITLE
TypeError: filters.some is not a function                                                                                          

### ISSUE THREAD

**Issue by boboldehampsink** [nuxt/test-utils#305]
When updating from 3.0.0.rc9 to 3.3.1 I see this error:

```
 ERROR  TypeError: filters.some is not a function                                                                                          16:18:54

 ❯ node_modules/vitest/dist/chunk-vite-node-externalize.6956d2d9.mjs:10719:51                                                              16:18:54
 ❯ Vitest.globTestFiles node_modules/vitest/dist/chunk-vite-node-externalize.6956d2d9.mjs:10719:29                                         16:18:54
 ❯ process.processTicksAndRejections node:internal/process/task_queues:95:5                                                                16:18:54
 ❯ Vitest.start node_modules/vitest/dist/chunk-vite-node-externalize.6956d2d9.mjs:10472:50                                                 16:18:54
 ❯ startVitest node_modules/vitest/dist/chunk-vite-node-externalize.6956d2d9.mjs:11204:5                                                   16:18:54
 ❯ runTests node_modules/@nuxt/test-utils/dist/index.mjs:311:21                                                                            16:18:54
 ❯ Object.invoke node_modules/nuxi/dist/chunks/test.mjs:14:5                                                                               16:18:54
 ❯ _main node_modules/nuxi/dist/cli.mjs:49:20      
```
