### ISSUE TITLE
Bug: v0.7.0 - Error while requiring module `vitest-environment-nuxt/module`: Error: Cannot find module 'vitest-environment-nuxt/module'

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/test-utils#584]
It seems after upgrading to 0.7.0 with vitest 0.31 I receive the error:
```
Error while requiring module `vitest-environment-nuxt/module`: Error: Cannot find module 'vitest-environment-nuxt/module'
```

Which looks like it is trying to be installed by the module required for this package.

Strange though as I see `vitest-environment-nuxt` as a dependency in the package.json

It could be @nuxt/test-utils > vitest conflicting versions. I'll do some digging.
